// Builds the Folio UI into web/dist (index.html, app.js, app.css). Run: npm run build [-- --dev]
import * as esbuild from 'esbuild';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.dirname(fileURLToPath(import.meta.url));
const dev = process.argv.includes('--dev');
const src = path.join(root, 'src');
const dist = path.join(root, 'dist');
fs.mkdirSync(dist, { recursive: true });

// 1) icons: collect every icon name used in the sources and pull the paths from lucide-static
const files = [];
(function walk(d) { for (const f of fs.readdirSync(d)) { const p = path.join(d, f); if (fs.statSync(p).isDirectory()) walk(p); else if (p.endsWith('.js') && !p.endsWith('icons.gen.js')) files.push(p); } })(src);
const names = new Set(['x', 'check', 'chevron-right', 'chevron-down', 'file-text', 'file', 'code-xml', 'message-square']);
const re = [/\bI\(\s*'([a-z0-9-]+)'/g, /\bicon:\s*'([a-z0-9-]+)'/g, /data-icon="([a-z0-9-]+)"/g, /\/\*icon\*\/\s*'([a-z0-9-]+)'/g];
// "soft" matches (ternaries inside I(...), ['id', 'icon'] tuples) are kept only when lucide has such an icon
const soft = [/\bI\((?:[^()]|\([^()]*\))*?\?\s*'([a-z0-9-]+)'\s*:\s*'([a-z0-9-]+)'/g, /\[\s*'[a-zA-Z.]+'\s*,\s*'([a-z0-9-]+)'\s*(?:,\s*'[^']*'\s*)?\]/g];
const iconDir = path.join(root, 'node_modules', 'lucide-static', 'icons');
for (const f of files) {
  const s = fs.readFileSync(f, 'utf8');
  for (const r of re) for (const m of s.matchAll(r)) names.add(m[1]);
  for (const r of soft) for (const m of s.matchAll(r)) for (const n of m.slice(1)) if (n && fs.existsSync(path.join(iconDir, n + '.svg'))) names.add(n);
}
const icons = {};
const missing = [];
for (const n of [...names].sort()) {
  const p = path.join(iconDir, n + '.svg');
  if (!fs.existsSync(p)) { missing.push(n); continue; }
  const svg = fs.readFileSync(p, 'utf8');
  icons[n] = svg.replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '').replace(/\s*\n\s*/g, '').trim();
}
if (missing.length) console.warn('missing icons:', missing.join(', '));
fs.writeFileSync(path.join(src, 'icons.gen.js'), '// generated by build.mjs from lucide-static (ISC license)\nexport default ' + JSON.stringify(icons) + ';\n');

// 3) i18n: every key used in the sources must exist in ru.js; en.js and zh.js must cover ru.js
{
  const { pathToFileURL } = await import('node:url');
  const load = async f => (await import(pathToFileURL(path.join(src, 'lang', f)).href + '?t=' + Date.now())).default;
  const [ru, en, zh] = await Promise.all(['ru.js', 'en.js', 'zh.js'].map(load));
  const used = new Set();
  const read = f => fs.readFileSync(f, 'utf8');
  for (const f of files) {
    if (f.includes(path.sep + 'lang' + path.sep)) continue;
    const s = read(f);
    for (const m of s.matchAll(/\bt\(\s*'([A-Za-z0-9_.-]+)'\s*[,)]/g)) used.add(m[1]);
    for (const m of s.matchAll(/\bt\([^()]*?\?\s*'([A-Za-z0-9_.-]+)'\s*:\s*'([A-Za-z0-9_.-]+)'/g)) { used.add(m[1]); used.add(m[2]); }
  }
  const appSrc = read(path.join(src, 'app.js'));
  for (const m of appSrc.matchAll(/\{ id: '([a-zA-Z0-9.]+)'/g)) used.add('cmd.' + m[1]);
  const setSrc = read(path.join(src, 'ui', 'settings-ui.js'));
  for (const m of setSrc.matchAll(/\b(tg|sel|slider|txt|fontRow)\('([a-zA-Z0-9]+)'/g)) used.add('set.' + m[2]);
  for (const sec of ['general', 'appearance', 'editor', 'reader', 'encodings', 'proof', 'ai', 'keys', 'updates', 'advanced', 'support']) { used.add('set.' + sec); used.add('set.' + sec + '.d'); }
  for (const m of ['standard', 'coder', 'proof']) { used.add('mode.' + m); used.add('mode.' + m + '.d'); }
  for (const m of ['file', 'edit', 'view', 'enc', 'tools', 'ai', 'help']) used.add('mb.' + m);
  for (const th of ['paper', 'graphite', 'sepia', 'glass', 'system']) used.add('theme.' + th);
  for (const k of ['fix', 'shorten', 'polite', 'translate', 'continue', 'explain', 'summary', 'chat']) used.add('ai.task.' + k);
  for (const c of ['error', 'config', 'cancelled', 'timeout', 'network', 'auth', 'billing', 'notFound', 'rateLimit', 'server', 'http', 'format', 'changed', 'empty', 'model']) { used.add('aiErr.' + c); used.add('aiErr.' + c + '.t'); }
  for (const f of ['markdown', 'plain', 'quote']) used.add('fmt.' + f);
  for (const k of ['all', 'info', 'warn', 'error']) used.add('logs.' + k);
  for (const f of files) for (const m of read(f).matchAll(/'((?:g|keys|stats|err|qn|tray)\.[a-zA-Z0-9]+)'/g)) used.add(m[1]);
  for (const k of ['key', 'tray.balloon', 'set.systemTheme', 'stats.js']) used.delete(k);
  for (const k of [...used]) if (k.endsWith('.') || /^keys\.ctrl/.test(k)) used.delete(k);
  const missing = [...used].filter(k => !(k in ru)).sort();
  const noEn = Object.keys(ru).filter(k => !(k in en));
  const noZh = Object.keys(ru).filter(k => !(k in zh));
  const extraEn = Object.keys(en).filter(k => !(k in ru));
  if (missing.length) console.warn(`i18n: ${missing.length} keys missing in ru.js:\n  ` + missing.join('\n  '));
  if (noEn.length) console.warn(`i18n: ${noEn.length} keys missing in en.js: ` + noEn.slice(0, 40).join(', '));
  if (noZh.length) console.warn(`i18n: ${noZh.length} keys missing in zh.js: ` + noZh.slice(0, 40).join(', '));
  if (extraEn.length) console.warn(`i18n: ${extraEn.length} keys only in en.js: ` + extraEn.join(', '));
  if (process.argv.includes('--strict') && (missing.length || noEn.length || noZh.length)) process.exit(1);
}

// 4) strings for the native parts (tray menu, quick note window, file dialogs) before the UI has started once
{
  const { pathToFileURL } = await import('node:url');
  const load = async f => (await import(pathToFileURL(path.join(src, 'lang', f)).href + '?n=' + Date.now())).default;
  const tables = Object.fromEntries(await Promise.all(['ru', 'en', 'zh'].map(async l => [l, await load(l + '.js')])));
  const appSrc = fs.readFileSync(path.join(src, 'app.js'), 'utf8');
  const m = /const NATIVE_KEYS = \[([\s\S]*?)\];/.exec(appSrc);
  const keys = m ? [...m[1].matchAll(/'([^']+)'/g)].map(x => x[1]) : [];
  const cs = s => JSON.stringify(String(s));
  const body = Object.entries(tables).map(([l, tb]) => `        [${cs(l)}] = new()\n        {\n${keys.filter(k => k in tb).map(k => `            [${cs(k)}] = ${cs(tb[k])},`).join('\n')}\n        },`).join('\n');
  const out = `// generated by web/build.mjs from web/src/lang/*.js — do not edit\nnamespace Folio;\n\ninternal static class NativeStrings\n{\n    public static readonly Dictionary<string, Dictionary<string, string>> Tables = new()\n    {\n${body}\n    };\n}\n`;
  const target = path.join(root, '..', 'src', 'Folio', 'NativeStrings.g.cs');
  if (fs.existsSync(path.dirname(target)) && (!fs.existsSync(target) || fs.readFileSync(target, 'utf8') !== out)) fs.writeFileSync(target, out);
}

// 2) bundle JS + CSS
await esbuild.build({
  entryPoints: { app: path.join(src, 'main.js') },
  bundle: true, format: 'iife', target: ['chrome110'], outdir: dist,
  minify: !dev, sourcemap: dev ? 'inline' : false, legalComments: 'none', charset: 'utf8',
  define: { __DEV__: String(dev), __VERSION__: JSON.stringify(JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8')).version) },
  logLevel: 'warning',
});
await esbuild.build({
  entryPoints: { app: path.join(src, 'css', 'index.css') },
  bundle: true, outdir: dist, minify: !dev, target: ['chrome110'], charset: 'utf8', logLevel: 'warning',
  loader: { '.woff2': 'dataurl' },
});
fs.copyFileSync(path.join(src, 'fonts.css'), path.join(dist, 'fonts.css'));
fs.copyFileSync(path.join(src, 'index.html'), path.join(dist, 'index.html'));
fs.copyFileSync(path.join(src, 'guard.js'), path.join(dist, 'guard.js'));
const size = f => (fs.statSync(path.join(dist, f)).size / 1024).toFixed(0) + ' KB';
console.log('built:', ['index.html', 'app.js', 'app.css', 'fonts.css'].map(f => f + ' ' + size(f)).join(', '), '| icons:', Object.keys(icons).length);
